services:
  nginx:
    ports:
      - 80:80

  backend:
    image: 
      235108306082.dkr.ecr.ap-south-1.amazonaws.com/key-ring:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    build:
      context: .
      args:
        - NODE_ENV=production
    command: node ./src/server.js