name: CD

on:
  workflow_run:
    workflows: ["Deploy doker image to Amazon ECR"]
    types:
      - completed

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}                   
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}           

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Deploy
      env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{ secrets.EC2_PUBLIC_IP }}
          USER_NAME: ${{ secrets.EC2_USER_NAME }}
    
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            # Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/app/Key-Ring &&
            git checkout prod &&
            git fetch --all &&
            git reset --hard origin/prod &&
            git pull origin prod &&
            make deploy
            '