name: CD

on:
  workflow_run:
    workflows: ["Deploy doker image to Amazon ECR"]
    types:
      - completed

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}                   
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}           

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Move to the directory containing the Dockerfile
      run: |
        cd ~
        cd ./app/Key-Ring

    - name: Update git branch
      run: git pull origin prod

    - name: Update Deployment
      run: make deploy
